name: "DT1_ABCDEF"

connections:
  mqtt:
    broker_url: "localhost"
    port: 1883
    topics:
    - "test/#"
    - "control"
  mongodb:
    use: yes
    url: "mongodb://localhost:27017"
    database: "pt"
    collection: "events"

  buffer:
    size: 100

process:
  buffer:
    size: 100
  burn:
    workers: 0
    work: 1000

state:
  max_size_mb: 1


migration:
  live:
    rounds: 10

metrics:
  file_name: "metrics.log"